apiVersion: apps/v1
kind: Deployment
metadata:
  name: <NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      #Matches template labels
      run: <NAME>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        # Gets matched by the Deployment and the Service-network.
        run: <NAME>
    spec:
      containers:
        - name: <NAME>
          image: <IMAGE NAME>
          ports:
            - containerPort: 80
          # Resource restrictions can be enabled
          # resources:
          #   requests:
          #     cpu: 100m
          #   limits:
          #     cpu: 100m
      # imagePullSecrets:
      #   - name: <PULL SECRET>
---
# Network-service for deployment above
apiVersion: v1
kind: Service
metadata:
  name: <NAME>-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    # Matches labels of pods (templates inside the deployment above)
    run: <NAME>
---
# Nginx Ingress for Domain with Letsencrypt SSL
apiVersion: v1
kind: Ingress
metadata:
  name: <NAME>-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - <DOMAIN>
      secretName: <DOMAIN CERT>
  rules:
    - host: <DOMAIN>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <NAME>-service
                port:
                  number: 80
